### ISSUE TITLE
Bug: supabase sign in db connect to auth

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#100]
<img width="1141" alt="Screenshot 2024-06-26 at 3 13 45 PM" src="https://github.com/trypear/pear-landing-page/assets/5115108/306ad4ab-17a9-4c92-8b9d-c67c6d02c80c">

user id is supposed to be filled, its not by default

**Comment by ItWasEnder** [comment]
Resolved: https://github.com/trypear/pearai-blobs/commit/813309545c27de338e2432c575a9ac8c96c69955

**Comment by nang-dev** [comment]
ender op
