### ISSUE TITLE
Update Password Page

### ISSUE THREAD

**Issue by Ellahinator** [trypear/pear-landing-page#104]
We need an `update-password` page which is a page that users get redirected to if they want to reset their password.

This is a simple page that just needs two form inputs `password` and `confirmPassword` and a `Update Password` button.

We need form validation to make sure the passwords match and are a minimum of 8 characters.

ex: (random image we obviously want to stick to our own theme)
![image](https://github.com/trypear/pear-landing-page/assets/87584757/77bcf8e4-04f8-4d0f-a910-27f5f0cdf186)

**Comment by SHADOW-LIGHTS** [comment]
working on this
