### ISSUE TITLE
Add sign-in page to landing page

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#12]
We need to add a sign-in button to the home page on the top right! 

It should go to a third party service (supabase) sign-in page to create them an account if needed. I think ender mentioned clerk, supabase, firebase, supertokens, auth0. 

Their email/pass should be stored in a way that they can sign in on the app with these credentials!

**Comment by shrix1** [comment]
I will work on it @nang-dev

**Comment by shrix1** [comment]
should i add shadcnUI , otherwise ui thing is hard rn

**Comment by Fryingpannn** [comment]
I've signed up for Google OAuth, if want your email to be added to test users pls ping me with ur email in discord. 

Related: need privacy policy and TOS
https://github.com/trypear/pear-landing-page/pull/16

**Comment by Ellahinator** [comment]
Draft PR 
- #20

**Comment by Tsounguinzo** [comment]
Is this ticket still open? I could submit a PR with clerk auth

**Comment by shrix1** [comment]
No Auth feature is already done @Tsounguinzo

**Comment by Pythonwithsean** [comment]
@Fryingpannn @nang-dev this issue is closed please can you close it
