### ISSUE TITLE
Bug - Mobile Menu Fails to Display Settings/Signout Options for Signed-In Users

### ISSUE THREAD

**Issue by Ellahinator** [trypear/pear-landing-page#121]
On **mobile** devices, the mobile menu component does not correctly render the "Settings" and "Signout" options when a user is signed in. Instead, it only displays "Signin" and "Signup" options, regardless of whether the user is authenticated.

**Expected Behavior:**
After signing in, the mobile menu should dynamically update to display options such as "Settings" and "Signout", reflecting the authenticated user's status.

![Image](https://github.com/trypear/pear-landing-page/assets/87584757/d3f54890-828a-4269-bf7f-6f20155a5ecb)

**Actual Behavior:**
The mobile menu persists in displaying only "Signin" and "Signup" options, failing to reflect the signed-in status of the user.
![Image](https://github.com/trypear/pear-landing-page/assets/87584757/c386196f-a76c-4fcd-b41d-5e12ae5116ca)

This results in users being unable to navigate to the Settings page or sign out. 

You can use [`authbutton.tsx`](https://github.com/trypear/pear-landing-page/blob/main/components/ui/authbutton.tsx) as a reference to see how the sign out functionality was handled.

**Comment by tomasohCHOM** [comment]
Can I take a look into this issue?

**Comment by Ellahinator** [comment]
@tomasohCHOM yes!
