### ISSUE TITLE
Enable dark mode for landing page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#122]
What's needed?
- Design for dark mode
- Implementation for dark mode (button (moon emoji) to turn dark or light)

We need code to be clean and modular for the implementation. E.g. if we want to switch colors it should be an easy change, not have to change a bunch of stuff.

**Comment by Ibinola** [comment]
can work on this

**Comment by xinov-bits** [comment]
I've started working on it, just need some confirmation on a few things:
- Is the color for dark mode fine?
- Should I change the design of the dark/light mode toggle button like a switch or something else?

![image](https://github.com/trypear/pear-landing-page/assets/85986123/7f48b0d1-41d3-4c20-a004-824d9b9a541f)

**Comment by tanishq-xin** [comment]
lighter design:
![image](https://github.com/trypear/pear-landing-page/assets/85986123/f9338e09-2257-4008-8511-dccc24462f53)

**Comment by ICEPrey** [comment]
lighter is better and the svg illustration top right might need to go
