### ISSUE TITLE
Add pricing and stripe checkout page to landing page

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#13]
We will offer 2 options to users

1. Free: use their own api-key, does not touch our server except for a couple basic pings for metrics (fully open sourced). Open-sourced, Fully transparent
2.  use our subscription, closed source to start, we can consider open sourcing this later. We offer this as the convenience for people who want it over transparency. and we outline exactly what we do with their data fully.

For the second, we should have a pricing page like:

Inspiration
![Image](https://github.com/trypear/pear-landing-page/assets/5115108/61d81efc-af9b-4a3b-8ede-7d32077295a7)

with filler text for now, 

that goes to a stripe checkout integration: https://stripe.com/payments/checkout

Relate: #50

**Comment by ICEPrey** [comment]
Our tech stack is similar so we can use this as inspiration. https://github.com/vercel/nextjs-subscription-payments
