### ISSUE TITLE
"Contact us for custom plans" redirecting back to pricing page

### ISSUE THREAD

**Issue by Zzzayaan** [trypear/pear-landing-page#143]
As cqdev on discord pointed out, on the pricing page there is a button to contact PearAI about custom plans, but currently the link just redirects right back to the same page. Instead, it should link to a new page.

![image](https://github.com/trypear/pear-landing-page/assets/99084167/4c2faa53-f2b7-4f97-bcd1-aa5c86f74d4e)

This new page should be called "Contact Us" which asks for information such as a person's full name, email, company, title and description. Cqdev also suggested an animation that plays to let the user know that the form been submitted.

**Comment by Zzzayaan** [comment]
I will be actively working on this issue!

**Comment by cqdev-co** [comment]
Let us know if you need any help!

**Comment by Fryingpannn** [comment]
Btw making some changes to this page from this PR https://github.com/trypear/pear-landing-page/pull/129/

**Comment by Dmedina20** [comment]
outdated
