### ISSUE TITLE
Separate pages for Contributing 101 and Pear Master doc

### ISSUE THREAD

**Issue by Alexx1105** [trypear/pear-landing-page#158]

**Comment by Alexx1105** [comment]
To make the website a bit more professional, it'd be a good idea to have "Contributing 101" and "Pear AI Master Doc" to have their own pages. They should be based off their slide / doc and even include a link to them in their (make the buttons to those links more creative/ eye-catching). The format/styling should be similar to this page: https://trypear.ai/about

**Comment by seanK04** [comment]
I am working on making the Pear AI Master Doc Page.
