### ISSUE TITLE
Persist callback URL if users goes from sign in to sign up - From PearAI desktop app

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#159]
## Current behaviour
- Click login from pearai desktop app
- Opens up landing page sign in page (with callback in URL query param)
  - at this point if user signs in, the callback will work as expected
  - however, if user doesn't have an account, they can click sign up
- If user clicks sign up, they lose the callback url, and after signing up, it won't open back the desktop pearai app.

## Expected behaviour
- If user logs in for desktop app, after webpage opens, even if user goes to sign up page, the callback query param should still be there, such that after sign up, on the settings page, it will prompt to open the dekstop app

## Info
- See `app/(auth)/signin/page.tsx` for example of existing callback logic.
- Can mock login from desktop flow by directly inputing `localhost:3000/signin?callback=code-oss://pearai.pearai/auth` into your browser search. This is what the desktop app will do when clicking on log in.
- Related previous issue https://github.com/trypear/pear-landing-page/issues/118 and pr https://github.com/trypear/pear-landing-page/pull/135

**Comment by dscreet** [comment]
I can work on this @Fryingpannn

**Comment by Dmedina20** [comment]
issue fixed
