### ISSUE TITLE
Revamping Github section of Landing Page

### ISSUE THREAD

**Issue by seanK04** [trypear/pear-landing-page#169]
Currently, clicking "GitHub" on the navbar leads to the pearai-app repository. Instead, we should create a page that features all three repositories related to pearai - App Repository, Submodule Repository, Landing Page Repository. There will be links and short descriptions for each of these repositories and their purposes.

**Comment by Fryingpannn** [comment]
Great idea

**Comment by seanK04** [comment]
I will work on making this page
