### ISSUE TITLE
Make navbar chosen tab change colour

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#179]
If the user is on the about page, currently the navbar text has no color change, so the user can get confused about which page they're on.

Expected behaviour should be that on whichever tab the user is on, the text on the navbar for that page should change color (the green that the rest of pages uses).

**Comment by SHADOW-LIGHTS** [comment]
Working on this

**Comment by Fryingpannn** [comment]
@SHADOW-LIGHTS ty, what's ur discord name?

**Comment by SHADOW-LIGHTS** [comment]
"Light" is the username
