### ISSUE TITLE
Need Pull-Request and Issue templates

### ISSUE THREAD

**Issue by shrix1** [trypear/pear-landing-page#18]
- Need Pull-Request , Issue template

**Comment by Fryingpannn** [comment]
In the issue template, need inform to tag the correct project sprint board on the right side. Which in turn will add it automatically to the board.

**Comment by Ibinola** [comment]
can i take this ?

**Comment by shrix1** [comment]
yaa take it @Ibinola

**Comment by Ibinola** [comment]
created a pr - https://github.com/trypear/pear-landing-page/pull/93
