### ISSUE TITLE
new page "Thanks for Downloading!"  🗃️

### ISSUE THREAD

**Issue by wflore19** [trypear/pear-landing-page#182]
### Description

Clicking the download button should redirect to a new page "Thanks for downloading PearAI! abcd..." where the download will take place.

### Expected Behavior

Download redirects to new page

### Actual Behavior

Download works but page is static

### Additional Information

name could be "download-confirmation" in `/page` and `/components` folders

**Comment by Alvarixxs** [comment]
Could I take this?

**Comment by wflore19** [comment]
I think oms_2005 might have already done this
