### ISSUE TITLE
[Medium][LandingPage] Reflect Free Trial + Early Bird Price

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#192]
### Description

Landing page pricing page should have a note about the free trial + early bird pricing.

cc: @tanishq-xin for the early bird pricing design

I think free trial is just simple text change: "You can download PearAI for free and use our free trial to see how good it is!"

**Comment by tanishq-xin** [comment]
I'd love to work on this

**Comment by shradiphylleia** [comment]
i would like to take this up--if this is not halfway done

**Comment by ICEPrey** [comment]
i think this is also done
