### ISSUE TITLE
[Medium][LandingPage] Investigate login issues

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#217]
## Describe the bug

Go to our logging page and try google sign in, many times, you have to click more than once the button for it to work. Sometimes when you click log in with Google it doesn't do anything.

We need to fix this so that the login flow is smooth and bug free.

Edit: this seems to be a much bigger issue on mobile! clicking on Sign in with Google does nothing! just refreshes the page

**Comment by SHADOW-LIGHTS** [comment]
Will check on this

**Comment by Hi-Van** [comment]
Think I got it figured out, will put up a PR after some more manual testing

https://github.com/user-attachments/assets/5be523fb-4f67-4308-9f52-a38a1837fd12

**Comment by Ellahinator** [comment]
- fixed #222

**Comment by zuhaz** [comment]
![image](https://github.com/user-attachments/assets/d903d9e0-e7da-4c4e-90c6-38ca14ad7ddf)

Is this a known issue? I'm unable to signup via google/github.
