### ISSUE TITLE
Add strict typing

### ISSUE THREAD

**Issue by ItWasEnder** [trypear/pear-landing-page#23]
Strict typing helps catch errors early during development, provides better autocompletion and documentation, and makes the code more predictable and easier to refactor.

🤝 We must be strong 💪
> Use TypeScript and then set everything to type Any
> \- JavaScript User47

### ❌ Wrong ❌
This code is not compatible* with supabase SDK as `fullName` is not a field belonging to the data structure passed into `signUp()`
```js
const data = {
  email: formData.get("email") as string,
  password: formData.get("password") as string,
  fullName: formData.get("full-name") as string,
};
```
### 🟢 Good 🟢
This code directly follows the SDK and would throw an error if `fullName` was added tot he root of `data`
```js
const data: SignUpWithPasswordCredentials = {
  email: formData.get("email") as string,
  password: formData.get("password") as string,
  options: {
    data: {
      full_name: formData.get("full-name") as string,
    },
  }
};
```

**Comment by Dmedina20** [comment]
Can we close this? @nang-dev @Fryingpannn
