### ISSUE TITLE
[Medium][LandingPage+Server] Add enterprise tier

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#233]
We need an enterprise tier along with our existing ones on https://trypear.ai/pricing

This enterprise tier will be 35$/month per user for monthly subscription, and 30$/month per user for annual subscription.

Tasks
- Think about how to display these extra ones on the pricing page? (UI/UX)
- Enterprise tier will get a centralized billing option, where only one person (the business) has to buy the plan, then this person can choose to add more people to it. So only this one person will be charged for all users on the plan. This should involve
   - A separate section on the dashboard that indicates the total number of requests available (sum of # of users max quota in the plan).
   - A way for the user to add more people to its team through email. The invited user must accept the email to be added to the team officially, upon which their account will also have access to PearAI Pro.

**Comment by Ellahinator** [comment]
> Think about how to display these extra ones on the pricing page? (UI/UX)

maybe like cursor's [pricing](https://www.cursor.com/pricing) page? with a monthly and yearly tab and free / pro / enterprise cards.

![Image](https://github.com/user-attachments/assets/4f29daa5-71b2-4d07-848b-887e1bf49d29)



![Image](https://github.com/user-attachments/assets/288aa052-a0e9-4364-8aa2-e4e725dc2198)

**Comment by seanlodhammar** [comment]
I'll try to design the pricing page with the enterprise tier @Fryingpannn @Ellahinator
