### ISSUE TITLE
Add the credit (in USD) quota to the dashboard

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#255]
### Description

Right now its like:

![Screenshot 2024-09-01 at 7 50 46 PM](https://github.com/user-attachments/assets/6acf0297-a7bd-4ae5-95c8-8217e3bb2bbc)

We need to add the quota of the $ USD. 
ie. $1.50/15

 it should be in the quota details.

**Comment by SHADOW-LIGHTS** [comment]
requests should be removed and used should be added??

**Comment by Dmedina20** [comment]
outdated
