### ISSUE TITLE
"Open PearAI" button stops working after cancelling the alert window

### ISSUE THREAD

**Issue by Wigya** [trypear/pear-landing-page#263]
### Description

As in the title, when user clicks the "Open PearAI" button in `/dashboard` and cancels the alert window, the button becomes useless. User needs to refresh the website in order to use the button again.
### Steps to Reproduce

1. Go to https://trypear.ai/dashboard
2. Click "Open PearAI" button
3. Cancel the alert window
4. Click the "Open PearAI" button again

### Expected Behavior

The button should open the alert window.

### Actual Behavior

The button doesn't open the alert window

### Additional Information

https://github.com/user-attachments/assets/07cd25b2-4d9c-4b1a-bb90-57e59351d701

### Sprint Board Tag

General sprint board? (Someone correct me it's my first issue)

**Comment by Himanshu-Singh-Chauhan** [comment]
yo, this was annoying me, thanks for fixing this.
