### ISSUE TITLE
[2][Easy][LandingPage+Server] Upgrade subscription feature

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#271]
Currently when someone is subscribed to monthly and they want to upgrade to annual, they must wait until their subscription ends.

What we want:
- A monthly subscriber clicks a button called "Upgrade to annual" on the dashboard, which upgrades their subscription to the annual plan at the end of their current period.

Info
- Need to check Stripe API to see how to change subscription

**Comment by qimcis** [comment]
can i pick this one up?

**Comment by Fryingpannn** [comment]
@qimcis Yessir, did u also apply to the quest by any chance? What is ur discord tag?

**Comment by qimcis** [comment]
> [@qimcis](https://github.com/qimcis) Yessir, did u also apply to the quest by any chance? What is ur discord tag?

i did but i had forgotten to put this as my preference 😭 , my discord tag is @qimcis

**Comment by Dmedina20** [comment]
outdated
