### ISSUE TITLE
[0][Hard][Landing+Server] Enterprise Tier

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#272]
Currently
- We have a enterprise pricing on landing page https://trypear.ai/pricing
- But user is unable to checkout directly with it

Expected
- Checkout directly from landing page for enterprise tier
- On the dashboard, an enterprise user can create a new team if not existing already
- On dashboard, if already has team name, should show name, and ability to invite new member by email, and list of existing members and pending invite members. See example below:

Info
- Need database and Stripe (create new product + per seat pricing) changes Pan needs to do (https://pastebin.com/J6u6isek).

https://v0.dev/r/LZX0D5w0JAf

![Image](https://github.com/user-attachments/assets/0185e205-635e-4189-89b5-bd9dc4265e89)

![Image](https://github.com/user-attachments/assets/6240bb4b-88d1-4955-a52e-a6fb51b09c27)

![Image](https://github.com/user-attachments/assets/319fb1e9-0205-4b4b-9a68-3f88fb807c41)

**Comment by Ellahinator** [comment]
I'm down to do this.

**Comment by Dmedina20** [comment]
outdated
