### ISSUE TITLE
[1][Medium][LandingPage] Improve Documentation

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#275]
Our current documentation page (https://trypear.ai/docs/) is decent but can be improved.
- First, include certain missing things like the "Setup" section https://docs.continue.dev/setup/overview. Currently, we don't have clear documentation on how the user can use local/open source models. The configurations for these are indicated in the "Setup" section.
- Certain things will have to be tweaked/removed/replaced. For example the "Free trial" and "Best Overall Experience" needs modifications to fit current PearAI circumstance.
- Add screenshots from PearAI as needed.
- Can also investigate further on what improvements to documentation can be made for it to be even better. This is a crucial part of allowing people to onboard more easily onto PearAI.

**Comment by stormyy00** [comment]
can i work on this?

**Comment by Fryingpannn** [comment]
@stormyy00 Yessir, did you also apply for the quest? What's your discord tag?

**Comment by stormyy00** [comment]
@Fryingpannn Yep I applied. discord: stormyy_

**Comment by Fryingpannn** [comment]
@stormyy00 assigned ya! lfg 🔥

**Comment by charlwillia6** [comment]
Linked to: https://github.com/trypear/pearai-documentation/pull/14

**Comment by Dmedina20** [comment]
issue resolved
