### ISSUE TITLE
[0][Easy][LandingPage] Add download button for dev version of PearAI

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#276]
Apps: https://drive.google.com/drive/u/0/folders/1lxKEZG2iqee7L5PCPLwCSjcmQhDknJCW

For development on the submodule, it is not possible to run it in debug mode when using the notarized version of the app. So contributors need to download the unotarized version which is available at the link above. This link should be in our contributors page in our docs.

**Comment by Pockylee** [comment]
I'll like to take this!

**Comment by Pockylee** [comment]
Just linking it to the drive will be fine, right?
Should I make the file to our server so they can download it directly?

**Comment by itzamanjain** [comment]
Hi @Pockylee ,

I noticed that issue #276 (adding the download button for the dev version of PearAI) has been assigned to you for a few weeks. I was wondering if you are currently working on it or if you need any help. If you’re busy or need assistance, I’d be happy to contribute and help move it forward.

Let me know how things are going!

Thanks

**Comment by Pockylee** [comment]
So sorry I did not see the message, and I truly forgot this one.......
thank you so much for helping me out!
