### ISSUE TITLE
[1][Medium][LandingPage+Server] Top up quota feature

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#277]
Currently
- When users reaches their maximum PearAI Credits, they cannot send requests anymore and must wait till the next month

Expected
- When user reaches their limit, if they want to use more, they can go on the landing page, their dashboard, to purchase more credits to be used
- These extra credits remain on the user's account forever. Meaning, even if the month is over, the extra credits can be used by the user next month. We will likely need an extra field in redis as "extra credits", and when the user runs out of their regular monthly credits, only then it reaches into their Extra Credits for usage.

What options to provide?
"Choose how much extra PearAI credits you'd like to add to your account. The utilization of credits depend on the size of your prompts and generated responses (e.g. smaller prompts will use fewer credits). To help you estimate, on average, we've seen that 1$ equates to around 40 requests."
- 5$ Small Juicer
- 10$ Health Potion
- 15$ Double Exp

Each of these would provide the exact amount as extra credit into redis field `extra_credits`

Extra info for development help
- The function `process_logged_tokens` in the server is used to write in Redis the regular number of credits after each chat request.
- The function `calculate_total_usd_credits_used` in the server is used to read how much credits the user has left at the beginning of each chat request.

**Comment by SHADOW-LIGHTS** [comment]
Will work on this
