### ISSUE TITLE
Usage on Pro Dashboard should indicate that time period is monthly

### ISSUE THREAD

**Issue by eiddor** [trypear/pear-landing-page#282]
### Description

On the current Dashboard for Pro users, the PearAI Credit usage doesn't say that the time period is monthly, so it's not clear (and also sandwiched between two "annuals."

(originally opened incorrectly at: https://github.com/trypear/pearai-app/issues/330)

### Steps to Reproduce

1. View Subscription & Usage at https://trypear.ai/dashboard with an annual Pro plan.

### Expected Behavior

A clear indication that the time period is monthly

### Actual Behavior

The usage is displayed with no indication of how long the time period is and it is sandwiched between the "annual" plan labels giving the impression that the usage is for the "Current Period" which is one year.

### Additional Information

![image](https://github.com/user-attachments/assets/87ad1123-b40b-4c81-be77-5ba86feac049)

**Comment by eiddor** [comment]
Related: #283

**Comment by charlwillia6** [comment]
This seems to be handled by https://github.com/trypear/pear-landing-page/pull/285

**Comment by Dmedina20** [comment]
outdated - new landng page
