### ISSUE TITLE
[1][Easy] Add a /dev page to download development versions of pearAI

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#296]
### Description

A /dev page where we can download the dev versions from our servers (similar to how we do for the /download)

we need this because we can't run PearAI submodule within a signed PearAI :(

**Comment by Gravqc** [comment]
Hello,
I'd like to work on this issue, but I have a few questions to clarify the requirements:
1. Navigation to the /dev Page:
    * Currently, there's a /pricing page, and /download redirects to it. How are users expected to navigate to the new /dev page?
        * Will there be a link added to the main navigation menu, footer, or elsewhere on the site?
        * Is the /dev page intended to be accessed directly via URL, or should it be discoverable through the site's navigation?
2. Access to Development Builds:
    * How will the development versions be obtained for the /dev page?
        * Is there an existing API endpoint or storage location (e.g., cloud storage, server directory) where these builds are stored?
        * If not, is part of this issue to set up the backend infrastructure (e.g., API endpoints, storage solutions) for hosting and serving the dev builds?
3. Scope of the Implementation:
    * Is the expectation to create a fully functional /dev page that lists and allows users to download development builds?
        * Should the page include functionality to fetch and display the list of available dev builds?
    * Or is the goal to set up the /dev page's structure and layout now, with the content and functionality to be added in a future issue?
4. Design and Content Guidelines:
    * Are there specific design guidelines or components I should follow to ensure the /dev page aligns with the rest of the site?
        * Should the /dev page mimic the /pricing page in terms of layout and styling, or are there any unique design considerations?
5. User Access and Permissions:
    * Will the /dev page be publicly accessible to all users, or should access be restricted?
        * For example, should it be accessible only to logged-in users, users with specific roles, or developers?
I want to make sure I understand the requirement..
Thank you!

**Comment by charlwillia6** [comment]
@nang-dev @Fryingpannn - Just a suggestion, but I think a link to development builds should be in the Contributing 101 docs, or in the documentation section somewhere, maybe where there is more detailed documentation for developers. I don't think a direct link to the developer downloads should be on the main landing page. But, this is just a suggestion.

**Comment by charlwillia6** [comment]
Here are two possible suggestions of linking to the new /dev page:

![image](https://github.com/user-attachments/assets/7b71563d-4422-4045-9d31-cd20da05fd27)
![image](https://github.com/user-attachments/assets/71e84ad7-55d3-4ff9-b4f1-e143a4f29d73)

This insures that contributors can find the downloads, but it doesn't highlight the developer downloads link so that normal users will probably ignore it.

**Comment by itzamanjain** [comment]
Hey, I added a download button to the contributors.md file for downloading the development version of pearAI in this [PR](https://github.com/trypear/pearai-documentation/pull/16), which solves issue #276.

**Comment by Dmedina20** [comment]
Closing this issue as it seems to be completed @nang-dev
