### ISSUE TITLE
[0][Easy] Update FAQ Language (Suggestions)

### ISSUE THREAD

**Issue by charlwillia6** [trypear/pear-landing-page#302]
### Description

As suggested on Discord, update the following FAQ language to sound more professional: 
https://docs.google.com/document/d/1X-6-ILT3uqn2LHV9ur2i2K_jYyJ5ArNpTP_U9Po2nqo/edit

Then update the FAQ on the website after the appropriate edits have been approved.

Suggested edit is on page 2 of the Google Doc.

### Additional Information

As discussed here: https://discord.com/channels/1237009981803462729/1243593346300121108/1289290927059243048

**Comment by charlwillia6** [comment]
@nang-dev - I would like to take this one.  Also, I forked this repo and can update the FAQ once approved.  I already have suggested edits on page two of the Google Doc: https://docs.google.com/document/d/1X-6-ILT3uqn2LHV9ur2i2K_jYyJ5ArNpTP_U9Po2nqo/edit

**Comment by charlwillia6** [comment]
Also, is this replacing the current FAQ, or is this an amendment?

**Comment by charlwillia6** [comment]
PR submitted: https://github.com/trypear/pear-landing-page/pull/309

**Comment by Dmedina20** [comment]
issue resolved
