### ISSUE TITLE
[2][Hard] Make Contributing To Blog Page No-Code

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#305]
it would be incredible if the blog flow is no-code
So, user sign in, submit  a blog post (md file is just fine)

and a moderator can approve/not approve
and it will be added to prod

**Comment by seanlodhammar** [comment]
I can work on this

**Comment by itzamanjain** [comment]
Hi, can I work on this issue? I’ve worked on similar documentation features in a past project .
here it is https://venture-catalyst.vercel.app/docs/getting-started/introduction

**Comment by itzamanjain** [comment]
Hi @nang-dev,

Currently, we're storing blog content in lib/postData.tsx.

 I was wondering if we should consider moving the blog content to a database instead. If so, could you let me know which database we're using, or which one we should use? 

I don't have access to the backend, so I’d appreciate your guidance on this.

Thanks!

**Comment by itzamanjain** [comment]
Hey team,

I've just opened a PR that's still a work in progress. Currently, I've added the blog submission form, but I still need to integrate the blogs with the database and implement the admin approval system.

I'll keep you updated as I make progress on these next steps. Feel free to review what's done so far!

**Comment by Dmedina20** [comment]
issue resolved
