### ISSUE TITLE
Unable to Access PearAI Website from My Country Without VPN

### ISSUE THREAD

**Issue by fazzy12** [trypear/pear-landing-page#311]
### Issue: Unable to Access PearAI Website from My Country Without VPN

**Description:**
I am unable to access the PearAI website from my country unless I use a VPN. When I try to visit the site without a VPN, it either fails to load or appears to be blocked. This issue prevents me from accessing your resources, downloading the software, and viewing documentation.

**Steps to Reproduce:**
1. Visit [PearAI Website](https://https://trypear.ai) from my location without a VPN.
2. The site does not load or is restricted.
3. When I enable a VPN and connect from another region, the website becomes accessible.

**Expected Behavior:**
The website should be accessible without needing a VPN, allowing users from all regions to browse resources and download the software.

**Actual Behavior:**
The website is inaccessible from my country unless I use a VPN to bypass the restriction.

**Additional Information:**
- **Country:** Nigeria
- **Browser:** chrome

**Request:**
Could you please look into the issue of website accessibility without a VPN and ensure that users from my region can access the site? If geographical restrictions are in place, it would be helpful to know the reason, or if there is any alternative to access PearAI resources directly.

**Comment by mackysy** [comment]
Same here. I live in the Philippines and chat isnt working at all.

**Comment by Dmedina20** [comment]
@fazzy12  still having this issue?

**Comment by Dmedina20** [comment]
outdated issue
