### ISSUE TITLE
Add a "How did you hear about us?" at the sign up page

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#314]
### Description

this should be saved as a field into supabase

**Comment by itzamanjain** [comment]
Hi @nang-dev , can I pick up this issue? I'd like to work on it.

**Comment by itzamanjain** [comment]
@nang-dev  
should we add an empty input field where users can type freely, or should we provide a few options like Twitter/X, Google, etc.? Let me know your preference. I'd like to pick this up.
