### ISSUE TITLE
PearAI Landing Page Revamp to V2!

### ISSUE THREAD

**Issue by nang-dev** [trypear/pear-landing-page#326]
Looking to revamp our landing page to something dynamic and looking something like:
- should be animated
- Update the hero text to the current latest one on landing page (https://trypear.ai)
- text in the boxes will have to be updated since they currently don't reflect our functionalities. not sure yet what to put, maybe something about PearAI inventory, like the AI tools we integrate: Perplexity, aider, Continue, Claude 3.5... Need to think about it more.

![Image](https://github.com/user-attachments/assets/d40576da-ec18-4a8f-9a10-57c8afdd2804)

[Bounty](https://trypear.ai/blog/open-source-bounties): $300
To be elligible for bounty, first apply here to get accepted!: https://forms.gle/wMNeZTDsRFiKcUF9A

NOTE:
hey guys!! ty guys so much for the interest! We currently actually have no asset for this design. this was given to us by someone else who wanted to perform the redesign for us. we tried asking for more information but they haven't replied to us yet. so we thought we may need to get someone else on it. we need it to look really good!!

please hold off on it for 1-2 more days while we wait for the person's response! if they are now too busy to work on it. then it's free game for us! just waiting on that 🫡 feel free ping me on discord for updates. Also, if you think you're able to pull this design off without any asset given at all, then also do lmk 👀

**Comment by ICEPrey** [comment]
Ill start working on this tomorrow

**Comment by itzamanjain** [comment]
/attempting

If you provide the Figma design, it would be beneficial. @nang-dev

**Comment by akash3444** [comment]
@nang-dev @Fryingpannn Could you provide more details on this? How should the animation behave? Are we revamping only the hero section of the landing page? Also, if you could share the grid asset, that would be really helpful.

**Comment by Fryingpannn** [comment]
hey guys!! ty for the interest. We currently actually have no asset for this design. this was given to us by some agency who wanted to perform the redesign for us. we tried asking for more information but they haven't replied to us yet. so we thought we may need to hire someone else. we need to design to be REALLY good. 

please hold off on it for 1-2 more days while we wait for the agency's response! if they are now too busy to work on it. then it's free game for us! just waiting on that 🫡 feel free ping me on discord for updates

**Comment by SHADOW-LIGHTS** [comment]
I am half way there. Created all the elements. I will complete it anyway🤷‍♀️

**Comment by Fryingpannn** [comment]
Ohh sht OK excited to see it @SHADOW-LIGHTS

**Comment by Fryingpannn** [comment]
@qimcis yoyo I saw u applied and said can provide design help. do you have any idea on how the animation would look like for the design above? e.g. when scrolling, how should things move? when your mouse cursor goes around, how do you think things will react?

**Comment by akash3444** [comment]
@Fryingpannn, we could implement an animation where data flows from Llama instances to the input, and then from GPT to the output. What do you think?

https://github.com/user-attachments/assets/c7716f9e-67eb-4776-a096-8b43ea9fc620

**Comment by nkalpakis21** [comment]
hey all! if you need any help with the bounty payout process please give n0va a try!
https://www.n0va-io.com/discover/trypear/pear-landing-page

the developer will get paid out once the approved PR is merged 

if you have any other questions feel free to shoot me a message on X
https://x.com/Kalpizzy7

**Comment by nang-dev** [comment]
THIS IS ASSIGNED TO LIGHT! OUR GOAT!

**Comment by Rihanmulani12** [comment]
i just added backround animated stuff and working on hero section as you mentioned above. can i work on it ? 


https://github.com/user-attachments/assets/c1d48f44-6f6c-4c5b-807e-4d4100233947

**Comment by shrix1** [comment]
yo wassup, is this PR done ?
