### ISSUE TITLE
Hamburger Button UI/ Side bar Missing Github Link Button

### ISSUE THREAD

**Issue by AlistairMaul** [trypear/pear-landing-page#364]
### Description

When scrunched **the Github button link to the (https://github.com/trypear/pearai-master) page** that appears on the top isn't moved to the side along with pricing, and resources. The documentation is moved to the side but moved under resources which isn't really an issue.

### Steps to Reproduce

1.  Open the (https://trypear.ai/)
2. Horizontally squish your browser.
3. And the the top options should be moved to a hamburger button but like I said the Github Button is indeed missing.

### Expected Behavior

The github link should be present on the side bar.

### Actual Behavior

It is missing and can be confusing for anyone wanting to get to the Github and has the website in this resolution.

### Additional Information
https://github.com/user-attachments/assets/3b700362-1110-40f8-b302-6e3ca6b08828

This is for:
https://github.com/trypear/pear-landing-page

This is my first issue done let me know if I need to change anything*

**Comment by Dmedina20** [comment]
issue resolved in PR: https://github.com/trypear/pear-landing-page/pull/367
