### ISSUE TITLE
✨Landing Page: Navbar/Header implementation

### ISSUE THREAD

**Issue by Dmedina20** [trypear/pear-landing-page#49]
✨Implement Landing Page v7's Navbar and Header✨ ( This includes mobile navigation aswell )

Take in consideration the responsiveness for all screen sizes, even mobile.
 
Figma file: [Click Here](https://www.figma.com/design/yVJjhUlhUwwEDBul42yvB4/PearAI-stuff?node-id=0-1&t=obKguksqkyBH087v-1)

When starting this issue, please comment under this issue if you can started this task, so we don't have multiple people starting at once.

**Comment by somwrks** [comment]
I'm Som, working on hero section of the landing page
