### ISSUE TITLE
Re-record high quality gifs for landing page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#58]
Sht is pixelated rn

**Comment by seanlodhammar** [comment]
I'll pick this up

**Comment by Hi-Van** [comment]
Make sure to run the GIF through the [Google chrome lab image compressor](https://squoosh.app/). GIFs may be lossless by default and can create relatively large files. We should also have a way to serve images at different resolutions to optimize for limited connection speeds, but that's a different story.

**Comment by Dmedina20** [comment]
Pretty sure this has been completed
