### ISSUE TITLE
✨ Landing Page Hero Section Revamp

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#59]
## **Context**

We are revamping the landing page to the `landing page v7` design within this [Figma](https://www.figma.com/design/yVJjhUlhUwwEDBul42yvB4/PearAI-stuff?node-id=0-1&t=obKguksqkyBH087v-1) design.

Can also see the complete UI/UX Doc [here](https://docs.google.com/document/d/13gXwVKJgf__DnrlokYvD9QU6bZZAyFVBLAQXWxNLo_U/edit#heading=h.vi2g2n8z3gic).

Please keep coding on Selene's PR to continue this change #43 

For help and more, see the landing page implementation [discord thread](https://discord.com/channels/1237009981803462729/1251395278100103249).

## **This PR**

We need to update the hero section, which is the place every user sees when they first land. It is of utmost importance. For the logo `.svg`, Selene will provide it for us.

![Image](https://github.com/trypear/pear-landing-page/assets/59063950/49eda22f-a8a0-4c34-ac61-0a26cf117dc4)

## **When**

We need this ASAP, preferably before Friday.

**Comment by somwrks** [comment]
HIIIIII HELLLOOOOOOOOOO I AM WORKING ON HERO AND NAVBAR

**Comment by Ellahinator** [comment]
- https://github.com/sea-lene/pear-landing-page/pull/3

**Comment by dfl0** [comment]
Gonna make some progress on this
