### ISSUE TITLE
[v0 Bugfix] Fix Fade in Transition

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#64]
- Go to https://trypear.ai/
- Scroll down (fast)
- The animation takes a bit too long for the text and images to load: UX is janky

Task: make the fade in effect smooth. Whether user goes on page and scrolls down smoothly, or goes on page and scrolls down fast, things should appear as you'd expect them to and not lag behind.

**Comment by jspEclipse** [comment]
can I work on this?

**Comment by somwrks** [comment]
i can work on this too!
