### ISSUE TITLE
User Workflow: Fix sign in, sign out, and forget password pages

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#66]
Color scheme is wrong for the following pages. Should conform to rest of landing page. Also includes when you type inside the input boxes.

1. SIGN IN 
2. SIGN OUT
3. FORGET PASSWORD

SIGN IN
![Image](https://github.com/trypear/pear-landing-page/assets/59063950/7fa187f8-aa68-459d-8b34-5a24c6ab0034)

SIGN OUT
![Image](https://github.com/trypear/pear-landing-page/assets/59063950/5c9f37c3-39cd-414f-af70-69a774554a0c)

FORGET PASSWORD
![Image](https://github.com/trypear/pear-landing-page/assets/59063950/ddf20035-1982-4a72-b9d3-d0c90fd8234b)

**Comment by dscreet** [comment]
can work on this

**Comment by triple-lutz** [comment]
@Fryingpannn curious to know - as I am new to this repo - is our landing page responsive to light/dark mode?

**Comment by jspEclipse** [comment]
> [@Fryingpannn](https://github.com/Fryingpannn) curious to know - as I am new to this repo - is our landing page responsive to light/dark mode?

as of the current moment, no it isn't. I also don't know if there are any plans on making it either.

**Comment by dscreet** [comment]
https://github.com/trypear/pear-landing-page/pull/92

**Comment by dscreet** [comment]
I'm assuming @Fryingpannn meant sign up page, not sign out.

Further work: modify Label and Input components and use these instead.
