### ISSUE TITLE
Improve trypear.ai SEO

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#77]
Our website is third Sadge. How can we beat pear.ai???????
![Image](https://github.com/trypear/pear-landing-page/assets/59063950/cb5d0bf0-82b6-439f-8ee7-00b876d58877)

**Comment by Fryingpannn** [comment]
@fumble is working onthis!

**Comment by shrix1** [comment]
@Fryingpannn From code side seo setup is good, pearai keywords for our site is not ranked, we need more click rate, Use `google search console` or `ahref` to track SEO stuffs

**Comment by Fryingpannn** [comment]
THANK U GUYS!

**Comment by akash3444** [comment]
@Fryingpannn We've outperformed pear.ai and now rank first when someone searches for pearai. We can close this issue now.
![image](https://github.com/user-attachments/assets/cfcce2fa-dc7d-4670-8cdb-32f30f236124)
