### ISSUE TITLE
Settings page on landing page

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#90]
## Context
Need a page for users to see when they are signed in which shows basic account info + subscription and usage information. Right now not a lot to display. Should look like something below:

The information within the boxes displayed should be aligned correctly. E.g.
```
Name           Duke Pan
Email Address  Something@gmail.com
```

![Image](https://github.com/trypear/pear-landing-page/assets/59063950/b943393e-3b6a-4612-aaf5-9387d559c956)

**Comment by jspEclipse** [comment]
can I take this?

**Comment by akash3444** [comment]
@jspEclipse If you are not planning to work on this, could you please assign it to me?

**Comment by akash3444** [comment]
#103
