### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#96]
We need form validation for all inputs of user workflows. Sign in, sign up and forget password inputs.

E.g. when user signs up, there's a 8 char minimum. Need client side validation if user presses sign up and doesn't have 8 chars, should error out and tell user. (Error message in red below input box that tells user "password not long enough")

![Image](https://github.com/trypear/pear-landing-page/assets/59063950/f8105410-e7d2-4acd-b2a1-a48d1971f975)

**Comment by Ibinola** [comment]
can i jump on this ?

**Comment by Ibinola** [comment]
just to clarify, do you mind if i use react hook form or custom functions?
