### ISSUE TITLE
Add `yarn prettier --write .` to build

### ISSUE THREAD

**Issue by Fryingpannn** [trypear/pear-landing-page#97]
Build fails because of linting too often. Need automate linting process in the CI pipeline. The command to fix linting errors is `yarn prettier --write .`.

**Comment by SHADOW-LIGHTS** [comment]
woking on this

**Comment by strawberrywz** [comment]
I can work on this.

**Comment by anisharaz** [comment]
The #89  pull request actually solves this by linting + formatting and then try to build the project before it commits, its all automatic at commit time  so no neet to do this at CI build time because if it failes at ci , a lot of time will waste just to lint, 
 format and commit again.

**Comment by Fryingpannn** [comment]
Thanks for the fix @anisharaz !
